### ISSUE TITLE
aospy supports python 3.5+, but conda-forge builds were for 2.7 and 3.6 only

### ISSUE THREAD

**Issue by spencerahill** [conda-forge/aospy-feedstock#14]
Issue:

Title says it all.  I couldn't find anything definitive in the documentation about how to control this, but I did find several candidates:  

- In [https://github.com/conda-forge/aospy-feedstock/tree/master/.ci_support](.ci_support) there are the 2.7 and 3.6 yaml files for each platform, but AFAICT they get automatically generated by conda smithy.  So I assume just deleting the 2.7 ones isn't the right path (nor would manually creating 3.7 ones).

- I also found [this section](https://conda.io/docs/user-guide/tasks/build-packages/variants.html#build-variants) of the conda docs about specifying build variants within a `conda_build_config.yaml` file, but I don't see that anywhere in our feedstock.  Do I just create it at the top level?

- I noticed in [xarray's conda_forge.yaml](https://github.com/conda-forge/xarray-feedstock/blob/master/conda-forge.yml) they have a `max_py_ver` option.  Is there an analogous `min_py_ver` option?

Please advise on how to fix this.  Thanks!

<br/>
Environment (<code>conda list</code>): n/a
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ): n/a
<details>

```
$ conda info

```
</details>

**Comment by ocefpaf** [comment]
The `max_py_ver` is added by the bot during the automatic migration but adding it manually, like you did in #16, is fine (sometimes it may fail due to missing dependencies though).

There is no `min_py_ver` b/c "current" python versions is handled using the `skip` statement. `max_py_ver` was a workaround for updating to Python 3.7 that we added to monitor the bot builds.

**Comment by spencerahill** [comment]
Ah, I see now.  Many thanks!

>the skip statement

I had seen this in the docs, but the example was for a particular platform (windows I believe), so I didn't realize it could be used for a python version also.  Although now in hindsight that makes perfect sense.
